name: Development

on:
  push:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby_version:
          - 2.7.7
          - 3.0.5
          - 3.1.3
        ar:
          - "~> 6.0.0"
          - "~> 6.1.0"
    env:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: 1
      AR: ${{ matrix.ar }}
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - run: bundle exec rake spec
